### ISSUE TITLE
New feature for placeholder

### ISSUE THREAD

**Issue by JuraRusan** [nulli0n/CoinsEngine-spigot#5]
Hello, I want to suggest a new placeholder, as I encountered a problem due to which the check in deluxe menus does not work.

Example: 
In the game I check the overall balance of players through: `/papi parse me %coinsengine_server_balance_coins%` and I get it at the exit `246,913,578` and accordingly, checking in the deluxe menus does not work because i have commas, and accordingly nothing is running for me
```
    left_click_requirement:
      requirements:
        balance_check:
          type: javascript
          expression: '%coinsengine_server_balance_coins% >= 64'
```
Deluxe menus [wiki](https://wiki.helpch.at/clips-plugins/deluxemenus/options-and-configurations/requirements#javascript)

But I came up with a small crutch in solving this problem. I'm using JavaScript placeholder API extensions and creating a custom placeholder for this.
```
var bal = '%coinsengine_server_balance_coins%' // 246,913,578

function placeholderBal() {
var sum = bal.replace(/,/g, '');
  return parseInt(sum, 10);
}

placeholderBal().toString(); // 246913578
```
But writing such a file for each currency is not very convenient. (in my case 12 pieces ¯\_(ツ)_/¯)
Therefore, I would like to suggest, for example, adding a placeholder in the form of `%coinsengine_server_balance_raw_[currency]%` which will display the value without commas.

Thank you in advance)
